# @package _global_

defaults:
  - _self_
  - datamodule: intel.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: timm.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

